### ISSUE TITLE
Sorting doesn't work

### ISSUE THREAD

**Issue by delgermurun** [tsmango/overcast-media-keys#4]
Hello, 

Thank you for great extension.

Sorting doesn't work.

Please take a look at it.

**Comment by tsmango** [comment]
Hey @delgermurun can you post a screenshot and point out where the sorting is broken? Seems to be working okay over here. Thanks!

**Comment by delgermurun** [comment]
Hi @tsmango, thanks for reply.

Here is frontpage screenshot

![screen shot 2017-02-22 at 9 05 38 am](https://cloud.githubusercontent.com/assets/492616/23192411/325cb650-f8de-11e6-994d-409da82aea4b.png)

I think "21 Feb"'s episodes should be on top of page, right?

Here is my options

![screen shot 2017-02-22 at 9 06 06 am](https://cloud.githubusercontent.com/assets/492616/23192413/35bbe3ac-f8de-11e6-897d-22a62058de82.png)

Seems like other options doesn't work too. Ex: Highlight In-Progress Episodes.

I guess I'm doing something wrong. No?

Thank you.

**Comment by tsmango** [comment]
Hmm okay so a few things, @delgermurun:

1. You have to check the "Sort Episodes by Date" option for that sort option to work. (Seems like I should make it so the two sort options below it are disabled unless the actual sort option is enabled, sorry about that!)
2. You do have the "prepend day of week" option checked, but from your screenshot, it doesn't seem to be prepending the date.
3. Otherwise, Marco recently modified the display of time remaining on episodes. Where it used to say "at" or "remaining", it now says "left". So that highlight feature broke. I have a fix ready to go and once we make sure your stuff is working - or I can reproduce and fix the issue you're seeing - I'll release an update to fix the highlight.

Let me know, thanks!

**Comment by delgermurun** [comment]
1. Sorting works. Thanks for explaining
2. "prepend day of week" now works too.
3. Highlight still not working. Let me know after update.

Thanks for quick fixes.

**Comment by tsmango** [comment]
Awesome, thanks for double checking those other settings. I've just published a update to the extension to fix that other highlighting issue that was introduced recently. Should go live in the extension directory in an hour or so. Enjoy!
